### PR TITLE
VMO-2573 flow validation for importing flows and validating against the spec. Contains important renames involving IResource and related classes

### PR DESCRIPTION
**Pull request by markboots**

### CODE REVIEW

**Comment by markboots** [comment]
Hi @bzabos @AlteaDown, I made some progress on flow validation this weekend, but came up against some things that could be best to discuss. Is this better to discuss in a huddle?

**Refactoring and implications on Android Channel:**

* See and review renames here: https://github.com/FLOIP/flow-runner/pull/36/commits/202726788322fa3eb658ff7e39ca7fbfdc0bd7a6

**Spec compatibility questions:**

* SupportedMode: casing of string values doesn't match spec and builder.
* SupportedContentType: needs to be an enum for validation; can't be used as enum in rest of code?  Casing of values doesn't match spec.
* SupportedContentType: builder is outputting an array with multiple values for SupportedContentType in resources. Should not happen according to spec. - Should we discuss resource structure?
* platform_metadata - when will this change?
* namespace char - when will this change?

**Build issues:**

* Could not "yarn build" without updating typescript; does that happen for others?
* With update, yarn eslint crashes on github post-commit checks

**Next steps for validation questions:**

* Can JSON Schema validate configs switching based on the block type? I couldn't find an easy way to describe this in JSON Schema (possibly the "if" concept?), or activate that via vega/ts-json-schema-generator
* What should we do for per-block config validation given this limitation?

**Comment by markboots** [comment]
Recapping our meeting decisions today with @bzabos and @AlteaDown : 

**Refactoring and implications on Android Channel:**

* See and review renames here: https://github.com/FLOIP/flow-runner/pull/36/commits/202726788322fa3eb658ff7e39ca7fbfdc0bd7a6
  * AGREED

**Spec compatibility questions:**

* SupportedMode: casing of string values doesn't match spec and builder.
  * Agreed that we will change the spec: casing so that the enum keys match the enum values (ie: "SMS", "RICH_MESSAGING")  This is most commonly the convention for enum-like values.
* SupportedContentType: needs to be an enum for validation; can't be used as enum in rest of code?  Casing of values doesn't match spec.
  * Change spec on casing
  * Convert from class to enum
  * Does not need to be a class, since it will not have extended values beyond the ones in the spec.
  * Will change "CSV" to "DATA" to cover any vendor-defined or extended Content Type. This will need a change in the Clipboard App.

* SupportedContentType: builder is outputting an array with multiple values for SupportedContentType in resources. Should not happen according to spec. - Should we discuss resource structure?
  * @bzabos and flow-builder team will fix in builder. Agreed this should be a single value for SupportedContentType
 
* platform_metadata - when will this change?
  * Will be fixed in upcoming sprint by flow-builder team
* namespace char - when will this change?
  * Will be fixed in upcoming sprint by flow-builder team 

**Build issues:**

* Could not "yarn build" without updating typescript; does that happen for others?
* With update, yarn eslint crashes on github post-commit checks
  * Agreed OK to upgrade to typescript 4.2.3. Just need to update ts-jest and eslint to go along with it.

**Next steps for validation questions:**

* Can JSON Schema validate configs switching based on the block type? I couldn't find an easy way to describe this in JSON Schema (possibly the "if" concept?), or activate that via vega/ts-json-schema-generator
* What should we do for per-block config validation given this limitation?
  * @bzabos @AlteaDown will research and propose how to handle within JSON Schema

**Comment by markboots** [comment]
@bzabos @AlteaDown , I updated the spec casing, and updated this PR based on our meeting yesterday. This is ready for your final review. Thanks!

**Comment by markboots** [comment]
(Spec casing changes I classified into the immaterial/typo category that doesn't need a community review, at this stage given there are no external affected users yet.)

**Review by bzabos — APPROVED** [review]
This has been working well on flow-builder, thanks @markboots! 

@safydy Looks like we're in a good spot with your stuff too. Let's merge!

**Pull request merged**
